version: '3'
services:
  backup_server:
    container_name: backupServer
    build:
      context: .
      dockerfile: backupServer/Dockerfile
    entrypoint: python3 backupServer/main.py
    environment:
      - BACKUP_SERVER_IP=backup_server
      - BACKUP_SERVER_PORT=12345
    networks:
      - my_network

  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    entrypoint: python3 client/main.py
    environment:
      - BACKUP_SERVER_IP=backup_server
      - BACKUP_SERVER_PORT=12345
      - SERVER_1_IP=server1
      - SERVER_1_PORT=12345
    stdin_open: true
    tty: true
    networks:
      - my_network
    depends_on:
      - backup_server

  server1:
    container_name: server1
    build:
      context: .
      dockerfile: server/Dockerfile
    entrypoint: python3 server/main.py
    environment:
      - SERVER_IP=server1
      - SERVER_PORT=12345
    networks:
      - my_network

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
