version: '3'
services:
  backup_server:
    container_name: backupServer
    build:
      context: .
      dockerfile: backupServer/Dockerfile
    entrypoint: python3 backupServer/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - BACKUP_SERVER_IP=backup_server
      - BACKUP_SERVER_PORT=12345
    networks:
      - my_network
    depends_on:
      - server1
    volumes:
      - ./backupServer/BackupRegistry:/BackupRegistry:rw
      - ./backupServer/BackupLog:/BackupLog:rw
      - ./backupServer/BackupStorage:/BackupStorage:rw

  client:
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    entrypoint: python3 client/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - BACKUP_SERVER_IP=backup_server
      - BACKUP_SERVER_PORT=12345
      - SERVER_1_IP=server1
      - SERVER_1_PORT=12345
      - SERVER_2_IP=server2
      - SERVER_2_PORT=12345
      - SERVER_3_IP=server3
      - SERVER_3_PORT=12345
    stdin_open: true
    tty: true
    networks:
      - my_network
    depends_on:
      - backup_server

  server1:
    container_name: server1
    build:
      context: .
      dockerfile: server/Dockerfile
    entrypoint: python3 server/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=server1
      - SERVER_PORT=12345
    networks:
      - my_network
    volumes:
      - ./server/Data:/Data:rw

  server2:
    container_name: server2
    build:
      context: .
      dockerfile: server/Dockerfile
    entrypoint: python3 server/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=server2
      - SERVER_PORT=12345
    networks:
      - my_network
    volumes:
      - ./server/Data:/Data:rw

  server3:
    container_name: server3
    build:
      context: .
      dockerfile: server/Dockerfile
    entrypoint: python3 server/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_IP=server3
      - SERVER_PORT=12345
    networks:
      - my_network
    volumes:
      - ./server/Data:/Data:rw

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
